In [1]:
import pandas as pd 
import numpy as np 
import tensorflow as tf 

2024-04-08 23:15:37.812825: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-04-08 23:15:37.812849: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
df = pd.read_csv('churn.csv')

In [3]:
print(df)

       CustomerID  Age  Gender  Tenure  Usage Frequency  Support Calls  \
0               1   22  Female      25               14              4   
1               2   41  Female      28               28              7   
2               3   47    Male      27               10              2   
3               4   35    Male       9               12              5   
4               5   53  Female      58               24              9   
...           ...  ...     ...     ...              ...            ...   
64369       64370   45  Female      33               12              6   
64370       64371   37    Male       6                1              5   
64371       64372   25    Male      39               14              8   
64372       64373   50  Female      18               19              7   
64373       64374   52  Female      45               15              9   

       Payment Delay Subscription Type Contract Length  Total Spend  \
0                 27             Basic  

In [4]:
exclude_indices = [0, 4, 5, 7, 11]

# Selecting columns other than the ones to exclude
x = df.iloc[:, [i for i in range(df.shape[1]) if i not in exclude_indices]]

In [5]:
print(x) 

       Age  Gender  Tenure  Payment Delay Contract Length  Total Spend  \
0       22  Female      25             27         Monthly          598   
1       41  Female      28             13         Monthly          584   
2       47    Male      27             29          Annual          757   
3       35    Male       9             17       Quarterly          232   
4       53  Female      58              2          Annual          533   
...    ...     ...     ...            ...             ...          ...   
64369   45  Female      33             21       Quarterly          947   
64370   37    Male       6             22          Annual          923   
64371   25    Male      39             30         Monthly          327   
64372   50  Female      18             22         Monthly          540   
64373   52  Female      45             25         Monthly          696   

       Last Interaction  
0                     9  
1                    20  
2                    21  
3      

In [6]:
y = df.iloc[:, -1].values

In [7]:
print(y)

[1 0 0 ... 1 1 1]


In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x.iloc[:, 1] = le.fit_transform(x.iloc[:, 1])


In [9]:
print(x)

       Age Gender  Tenure  Payment Delay Contract Length  Total Spend  \
0       22      0      25             27         Monthly          598   
1       41      0      28             13         Monthly          584   
2       47      1      27             29          Annual          757   
3       35      1       9             17       Quarterly          232   
4       53      0      58              2          Annual          533   
...    ...    ...     ...            ...             ...          ...   
64369   45      0      33             21       Quarterly          947   
64370   37      1       6             22          Annual          923   
64371   25      1      39             30         Monthly          327   
64372   50      0      18             22         Monthly          540   
64373   52      0      45             25         Monthly          696   

       Last Interaction  
0                     9  
1                    20  
2                    21  
3                  

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x.iloc[:, 4] = le.fit_transform(x.iloc[:, 4])


In [21]:
x

Age Gender  Tenure  Payment Delay Contract Length  Total Spend  \
0       22      0      25             27               1          598   
1       41      0      28             13               1          584   
2       47      1      27             29               0          757   
3       35      1       9             17               2          232   
4       53      0      58              2               0          533   
...    ...    ...     ...            ...             ...          ...   
64369   45      0      33             21               2          947   
64370   37      1       6             22               0          923   
64371   25      1      39             30               1          327   
64372   50      0      18             22               1          540   
64373   52      0      45             25               1          696   

       Last Interaction  
0                     9  
1                    20  
2                    21  
3                    18  
4                    18  
...                 ...  
64369                14  
64370                 9  
64371                20  
64372                13  
64373                22  

[64374 rows x 7 columns]

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_test = sc.fit_transform(x_test)
x_train = sc.fit_transform(x_train)

In [14]:
ann = tf.keras.models.Sequential()

2024-04-08 23:15:39.683396: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-04-08 23:15:39.683428: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-04-08 23:15:39.683444: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ali-Victus-by-HP-Gaming-Laptop-15-fb0xxx): /proc/driver/nvidia/version does not exist
2024-04-08 23:15:39.683599: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [15]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [16]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [18]:
ann.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])

In [19]:
ann.fit(x_train, y_train, batch_size=32, epochs=13)

Epoch 1/13
1610/1610 [==============================] - 1s 509us/step - loss: 0.4753 - accuracy: 0.7820
Epoch 2/13
1610/1610 [==============================] - 1s 505us/step - loss: 0.4252 - accuracy: 0.8184
Epoch 3/13
1610/1610 [==============================] - 1s 582us/step - loss: 0.4099 - accuracy: 0.8274
Epoch 4/13
1610/1610 [==============================] - 1s 592us/step - loss: 0.3977 - accuracy: 0.8333
Epoch 5/13
1610/1610 [==============================] - 1s 556us/step - loss: 0.3878 - accuracy: 0.8380
Epoch 6/13
1610/1610 [==============================] - 1s 526us/step - loss: 0.3800 - accuracy: 0.8409
Epoch 7/13
1610/1610 [==============================] - 1s 526us/step - loss: 0.3744 - accuracy: 0.8432
Epoch 8/13
1610/1610 [==============================] - 1s 525us/step - loss: 0.3699 - accuracy: 0.8458
Epoch 9/13
1610/1610 [==============================] - 1s 524us/step - loss: 0.3659 - accuracy: 0.8482
Epoch 10/13
1610/1610 [==============================] - 1s 536u

In [37]:
print((ann.predict(sc.transform([[22, 0, 25, 27, 1, 598, 9]])) > 0.5))

[[ True]]


/home/ali/.local/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [40]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix( y_test, y_pred)
print(cm)

[[0 0]
 [0 0]
 [1 1]
 ...
 [1 1]
 [1 0]
 [1 0]]
[[5758 1035]
 [ 775 5307]]


In [41]:
accuracy_score(y_test, y_pred)

0.8594174757281553